#!/usr/bin/env bash
# The demo's settings, in one place. Every script sources this; you can too:
#   source ~/agentops/activate.sh
# Writes diabetes_agent/.env (what `adk web`, `adk eval` and `adk deploy` all read) and
# activates the Python environment if setup.sh has created it.
#
# Three locations, and they are all different (worth a minute in class):
#   BQ_LOCATION      US           where the BigQuery dataset lives
#   GEMINI_LOCATION  global       where the MODEL is called (current Gemini models are global)
#   AGENT_REGION     us-central1  where the deployed AGENT runs (Agent Runtime needs a real region)

__ACT_SOURCED=0; [[ "${BASH_SOURCE[0]}" != "${0}" ]] && __ACT_SOURCED=1
__act_fail() { echo "ERROR: $*" >&2; if [[ $__ACT_SOURCED -eq 1 ]]; then return 1; else exit 1; fi; }

PROJECT_ID="${PROJECT_ID:-$(gcloud config get-value core/project 2>/dev/null || true)}"
if [[ -z "${PROJECT_ID}" || "${PROJECT_ID}" == "(unset)" ]]; then
  __act_fail "No project set. Run: gcloud config set project <your-project-id>" || return 1
fi
export PROJECT_ID
export DEMO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"

# BigQuery
export BQ_DATASET="${BQ_DATASET:-demo_diabetes}"
export BQ_LOCATION="${BQ_LOCATION:-US}"
export GCS_URI="${GCS_URI:-gs://class-demo/diabetes_prediction_dataset.csv}"

# Model and Agent Runtime
export GEMINI_LOCATION="${GEMINI_LOCATION:-global}"
export AGENT_REGION="${AGENT_REGION:-us-central1}"
export AGENT_MODEL="${AGENT_MODEL:-gemini-flash-latest}"
export AGENT_DISPLAY_NAME="${AGENT_DISPLAY_NAME:-Diabetes Risk Agent (AgentOps demo)}"

# Model Armor (M5). The template lives in the "us" multi-region.
export MA_LOCATION="${MA_LOCATION:-us}"
export MA_TEMPLATE_ID="${MA_TEMPLATE_ID:-diabetes-agent-guard}"
export MODEL_ARMOR_TEMPLATE="projects/${PROJECT_ID}/locations/${MA_LOCATION}/templates/${MA_TEMPLATE_ID}"

cat > "${DEMO_ROOT}/diabetes_agent/.env" <<ENVEOF
# Generated by activate.sh. Do not edit by hand: rerun  source ~/agentops/activate.sh
# GOOGLE_CLOUD_LOCATION is where the MODEL is served (global), not where the agent is deployed.
GOOGLE_GENAI_USE_ENTERPRISE=1
GOOGLE_CLOUD_PROJECT=${PROJECT_ID}
GOOGLE_CLOUD_LOCATION=${GEMINI_LOCATION}
PROJECT_ID=${PROJECT_ID}
BQ_DATASET=${BQ_DATASET}
AGENT_MODEL=${AGENT_MODEL}
MODEL_ARMOR_TEMPLATE=${MODEL_ARMOR_TEMPLATE}
# M3: put tool arguments and results into the trace spans, so the trace shows the SQL and the error.
# Great for debugging, and exactly the PII risk the M3 deck warns about. Set to false for real patient data.
ADK_CAPTURE_MESSAGE_CONTENT_IN_SPANS=true
ENVEOF

if [[ -f "${DEMO_ROOT}/.venv/bin/activate" && -z "${VIRTUAL_ENV:-}" ]]; then
  # shellcheck disable=SC1091
  source "${DEMO_ROOT}/.venv/bin/activate"
fi

if [[ "${ACTIVATE_QUIET:-0}" != "1" ]]; then
  echo "✓ diabetes_agent/.env written for ${PROJECT_ID}"
  echo "  model ${AGENT_MODEL} @ ${GEMINI_LOCATION} · agent region ${AGENT_REGION} · dataset ${BQ_DATASET} @ ${BQ_LOCATION}"
fi
